CREATE TABLE `comment_table` (
  `COMMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PRODUCT_ID` int(11) DEFAULT NULL,
  `COMMENT_USERNAME` varchar(50) DEFAULT NULL,
  `COMMENT_WORDS` varchar(200) DEFAULT NULL,
  `COMMENT_DATE` date DEFAULT NULL,
  `COMMENT_IMAGE` varchar(200) DEFAULT NULL,
  `COMMENT_VIDEO` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`COMMENT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8;



INSERT INTO shangcheng.comment_table
(COMMENT_ID, PRODUCT_ID, COMMENT_USERNAME, COMMENT_WORDS, COMMENT_DATE, COMMENT_IMAGE, COMMENT_VIDEO)
VALUES(1, 1, 'Alex', '这个茶叶味道不错', '2018-06-13', 'images/people.png', NULL);
INSERT INTO shangcheng.comment_table
(COMMENT_ID, PRODUCT_ID, COMMENT_USERNAME, COMMENT_WORDS, COMMENT_DATE, COMMENT_IMAGE, COMMENT_VIDEO)
VALUES(2, 1, 'Ming', '味道不错', '2017-02-03', 'images/people.png', NULL);
INSERT INTO shangcheng.comment_table
(COMMENT_ID, PRODUCT_ID, COMMENT_USERNAME, COMMENT_WORDS, COMMENT_DATE, COMMENT_IMAGE, COMMENT_VIDEO)
VALUES(3, 1, '123', '味道就那样吧', '2018-06-13', 'images/people.png', NULL);
INSERT INTO shangcheng.comment_table
(COMMENT_ID, PRODUCT_ID, COMMENT_USERNAME, COMMENT_WORDS, COMMENT_DATE, COMMENT_IMAGE, COMMENT_VIDEO)
VALUES(4, 1, '456', '一般般', '2018-06-13', 'images/people.png', NULL);
INSERT INTO shangcheng.comment_table
(COMMENT_ID, PRODUCT_ID, COMMENT_USERNAME, COMMENT_WORDS, COMMENT_DATE, COMMENT_IMAGE, COMMENT_VIDEO)
VALUES(5, 2, '123', '味道还行', '2018-06-13', 'images/people.png', NULL);
INSERT INTO shangcheng.comment_table
(COMMENT_ID, PRODUCT_ID, COMMENT_USERNAME, COMMENT_WORDS, COMMENT_DATE, COMMENT_IMAGE, COMMENT_VIDEO)
VALUES(6, 2, '456', '这个茶叶买的值', '2018-06-13', 'images/people.png', NULL);
INSERT INTO shangcheng.comment_table
(COMMENT_ID, PRODUCT_ID, COMMENT_USERNAME, COMMENT_WORDS, COMMENT_DATE, COMMENT_IMAGE, COMMENT_VIDEO)
VALUES(7, 3, '111', '看好这个茶', '2018-06-13', 'images/people.png', NULL);
INSERT INTO shangcheng.comment_table
(COMMENT_ID, PRODUCT_ID, COMMENT_USERNAME, COMMENT_WORDS, COMMENT_DATE, COMMENT_IMAGE, COMMENT_VIDEO)
VALUES(8, 3, '222', '不错哦', '2018-06-13', 'images/people.png', NULL);
INSERT INTO shangcheng.comment_table
(COMMENT_ID, PRODUCT_ID, COMMENT_USERNAME, COMMENT_WORDS, COMMENT_DATE, COMMENT_IMAGE, COMMENT_VIDEO)
VALUES(9, 3, '333', '还行', '2018-06-13', 'images/people.png', NULL);
INSERT INTO shangcheng.comment_table
(COMMENT_ID, PRODUCT_ID, COMMENT_USERNAME, COMMENT_WORDS, COMMENT_DATE, COMMENT_IMAGE, COMMENT_VIDEO)
VALUES(10, 3, '444', '还行', '2018-06-13', 'images/people.png', NULL);
INSERT INTO shangcheng.comment_table
(COMMENT_ID, PRODUCT_ID, COMMENT_USERNAME, COMMENT_WORDS, COMMENT_DATE, COMMENT_IMAGE, COMMENT_VIDEO)
VALUES(11, 3, '555', '不怎么样', '2018-06-13', 'images/people.png', NULL);
INSERT INTO shangcheng.comment_table
(COMMENT_ID, PRODUCT_ID, COMMENT_USERNAME, COMMENT_WORDS, COMMENT_DATE, COMMENT_IMAGE, COMMENT_VIDEO)
VALUES(13, 4, '111', '。。。', '2018-06-13', 'images/people.png', NULL);
INSERT INTO shangcheng.comment_table
(COMMENT_ID, PRODUCT_ID, COMMENT_USERNAME, COMMENT_WORDS, COMMENT_DATE, COMMENT_IMAGE, COMMENT_VIDEO)
VALUES(14, 3, 'Song', '非常好', '2018-06-13', 'images/people.png', NULL);
INSERT INTO shangcheng.comment_table
(COMMENT_ID, PRODUCT_ID, COMMENT_USERNAME, COMMENT_WORDS, COMMENT_DATE, COMMENT_IMAGE, COMMENT_VIDEO)
VALUES(15, 2, 'Ming', '123456', '2018-06-13', 'images/people.png', NULL);
INSERT INTO shangcheng.comment_table
(COMMENT_ID, PRODUCT_ID, COMMENT_USERNAME, COMMENT_WORDS, COMMENT_DATE, COMMENT_IMAGE, COMMENT_VIDEO)
VALUES(16, 4, '123456', '这个茶叶值得购买', '2018-06-13', 'images/people.png', 'null');
